# Create an admin user
User.create!(
    name: 'Admin User',
    email: 'admin@example.com',
    password: 'securepassword', # Make sure to use a strong password in a real application
    password_confirmation: 'securepassword',
    role: 'admin' # This depends on how your User model defines an admin
  )
  
  TaskCategory.create([
    { name: 'Web Development' },
    { name: 'Graphic Design' },
    { name: 'Content Writing' },
    { name: 'Digital Marketing' },
    { name: 'SEO Optimization' },
    { name: 'Mobile App Development' },
    { name: 'Social Media Management' },
    { name: 'Video Editing' },
    { name: 'Animation' },
    { name: 'Data Analysis' },
    { name: 'Cybersecurity' },
    { name: 'Software Testing' },
    { name: 'Technical Support' },
    { name: 'Cloud Computing' },
    { name: 'DevOps' },
    { name: 'UI/UX Design' },
    { name: 'E-commerce Development' },
    { name: 'Copywriting' },
    { name: 'Translation Services' },
    { name: 'Virtual Assistance' },
    { name: 'Photography' },
    { name: 'Voice Over' },
    { name: 'Illustration' },
    { name: 'Game Development' },
    { name: '3D Modeling' },
    { name: 'Blockchain Development' },
    { name: 'Machine Learning' },
    { name: 'Artificial Intelligence' },
    { name: 'Internet of Things (IoT)' },
    { name: 'Network Engineering' },
    { name: 'Database Management' },
    { name: 'Systems Administration' },
    { name: 'Embedded Systems' },
    { name: 'Robotics' },
    { name: 'Business Analysis' },
    { name: 'Financial Analysis' },
    { name: 'Project Management' },
    { name: 'Human Resources' },
    { name: 'Legal Consulting' },
    { name: 'Medical Writing' },
    { name: 'Scientific Research' },
    { name: 'Education & Tutoring' },
    { name: 'Counseling & Therapy' },
    { name: 'Health & Fitness Coaching' },
    { name: 'Event Planning' },
    { name: 'Interior Design' },
    { name: 'Architectural Design' },
    { name: 'Engineering' },
    { name: 'Market Research' },
    { name: 'Sales & Lead Generation' },
    { name: 'Customer Support' },
    { name: 'Technical Writing' },
    { name: 'Grant Writing' },
    { name: 'Resume Writing' },
    { name: 'Career Counseling' }
  ])
  